[package]
name = "sphinx"
version = "0.1.0"
authors = ["Ania Piotrowska <ania@nymtech.net>", "Dave Hrycyszyn <futurechimp@users.noreply.github.com>", "Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-ctr = "0.4"
bs58 = "0.3.0"
curve25519-dalek = "3.0.0"
hmac = "0.8"
digest = "0.9"
log = "0.4"
rand = {version = "0.7.3", features = ["wasm-bindgen"]}
rand_distr = "0.2.2"
sha2 = "0.9.1"
hkdf = "0.9.0"
#lioness = "0.1.2"
lioness = { git = "https://github.com/nymtech/lioness-rs", branch="iv_tests" }
arrayref = "0.3.5"
chacha = "0.3.0"
blake2 = "0.8.1"
byteorder = "1.3.2"
subtle = "2.3.0"

[dev-dependencies]
mockall = "0.5.2"
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false
